"""Added new column in databasee

Revision ID: 020abed02daa
Revises: 
Create Date: 2025-04-30 18:36:37.331815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020abed02daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
